### ISSUE TITLE
play.google.com POST and CORS error

### ISSUE THREAD

**Issue by widewideweb12** [hash3liZer/evilginx2#1]
Hi hash3liZer,

I am interested in your evilginx2 of 1 week.

I have passed all the stages but when I use Google.yaml economically, I get CORS error in the Chrome console.

https://prnt.sc/rj7z17

https://prnt.sc/rj7zba

Also, when I enter my fake domain, I write Google e-mail and password screen is not displayed.

Email is constantly being uploaded

I am waiting for your help on this subject

Thank you

*I CONFIRM*

Thanks!
--

**Comment by MikeTrust** [comment]
send me a mail and I will solve your issues (miketrust608@gmail.com)

**Comment by widewideweb12** [comment]
> send me a mail and I will solve your issues ([miketrust608@gmail.com](mailto:miketrust608@gmail.com))

hi,

After I wrote the problem here, I worked a little on it and I fixed the problem.

But Google enforced "oAuth" to prevent attacks with MITM in June 2019.

My Evilginx is running now, but browsers and Google are preventing the victim from logging in.

I'm leaving a screenshot.

https://prnt.sc/rl9dq3

**Comment by MikeTrust** [comment]
All my phishlet are working perfectly if you ready to pay I can help you
solve your problems....Can also give you link for confirmation

**Comment by MikeTrust** [comment]
What do you mean?
