### ISSUE TITLE
phishlet malfunction

### ISSUE THREAD

**Issue by horllste** [hash3liZer/evilginx2#10]
#### PLEASE READ THE POSTING GUIDELINES AND ANSWER THE QUESTION BEFORE POSTING, OTHERWISE ISSUE WILL BE CLOSED AND MARKED AS INVALID

* I hereby declare the following issue is a **[tool specific question/bug report]** and it is **NOT** a help request about creating a phishlet.
* I am fully aware that this is not a customer support portal, I can't demand answers and I'm aware I am using a free tool.
* I am not going to use Evilginx to hax my girlfriend's account or use it for any other illegal purpose.
* I am not trying to set up a domain on FreeNOM (also read the sentence above again).
* I am not a robot.
*(Sorry, if you are an adult and a professional and you had to read this.)*

Please type in "**I CONFIRM**" below if you confirm the sentences above or otherwise make some funny remark:

*I CONFIRM*

Thanks!
--
this is not really an issue, its more of a question.
i was wondering what could make a phishlet works perfectly locally and gives issues on a vps
thanks

**Comment by hash3liZer** [comment]
Hi, 

To make a phishlet perfectly work. You need to look upon filtration closely and observe each and individual requests through a proxy tool. Once you analyze all the requests, you need to closely look upon the filters to set what needs to be replaced etc. Hope it clears the question.

**Comment by horllste** [comment]
thanks, i have done that to the best of my knowledge and got the phishlet working on my pc, using localhost as domain. today i setup a server and run the same phishlet and got problems i dont know the causes.

**Comment by hash3liZer** [comment]
Can you put that on to my email?  ---- On Fri, 11 Sep 2020 00:13:05 +0500  notifications@github.com  wrote ----
thanks, i have done that to the best of my knowledge and got the phishlet working on my pc, using localhost as domain. today i setup a server and run the same phishlet and got problems i dont know the causes.

**Comment by horllste** [comment]
yes sure.
admin@shellvoide.com
is that the right email?

**Comment by hash3liZer** [comment]
Yes, i'll close the issue once you mailed me! ---- On Fri, 11 Sep 2020 00:25:11 +0500  notifications@github.com  wrote ----
yes sure.
admin@shellvoide.com
is that the right email?

**Comment by horllste** [comment]
i mailed you and i will close this
