### ISSUE TITLE
Error after MAKE command

### ISSUE THREAD

**Issue by bonyakamara** [hash3liZer/evilginx2#14]
I am trying to install evilginx2 and after inputting the make command, see attachment for the errors I see. Where is emanating from? Do you think it is my server or from the evilginx release?
Kindly assist with explanation.

![evil](https://user-images.githubusercontent.com/75266414/100634279-f2f46500-32e3-11eb-9bed-0dca50ab70ec.png)

**Comment by JamesCullum** [comment]
Do you have go installed? If so, is it the newest version?
Please try `go build` instead.

**Comment by bonyakamara** [comment]
I have the latest build of go installed `go version go1.15.5 linux/amd64`

At what point do I run the go build? After I have gotten into the evilginx2 directory?

```
sudo apt-get -y install git make
git clone https://github.com/hash3liZer/evilginx2.git
cd evilginx2
go build
```
Am I right on this?

**Comment by JamesCullum** [comment]
You don't need `make` in this case, but yes, that's correct.

**Comment by bonyakamara** [comment]
Thanks for your prompt response.

After running the `go build` I tried running this command

`sudo ./bin/evilginx -p ./phishlets/`

I ended up with the error 

sudo: ./bin/evilginx: command not found

I also tried running this other command for global install

`sudo make install`

I ended up with the error 

```
cp: cannot stat './bin/evilginx': No such file or directory
Makefile:15: recipe for target 'install' failed
make: *** [install] Error 1
```
Please what can I do next to remedy this?

**Comment by JamesCullum** [comment]
The executable built by `go build` should be named evilginx2 - can you make sure to check if it suceeds and is created?

**Comment by bonyakamara** [comment]
If inside of the evilginx2 folder then it is.

Kindly see attachment to verify if I understood what you meant.


![evil](https://user-images.githubusercontent.com/75266414/100647574-99e0fd00-32f4-11eb-9275-59e632b9d8c5.png)

**Comment by JamesCullum** [comment]
Yeah, the screenshot shows the evilginx2 executable. Run that one.

**Comment by bonyakamara** [comment]
Sorry to ask but which command do I run?

`sudo ./bin/evilginx -p ./phishlets/` gives error like I pointed out. Tried again and it logged `sudo: ./bin/evilginx: command not found`

**Comment by JamesCullum** [comment]
The command is the name of the executable. This means you need `sudo evilginx2`

**Comment by bonyakamara** [comment]
Annoyingly, here's the result

`sudo: evilginx2: command not found`

This, I don't know what has gone wrong.

**Comment by JamesCullum** [comment]
This sounds like an issue with your local setup - compilation works but you struggle to execute it. Let me know if you find an issue related directly to the tool.

**Comment by bonyakamara** [comment]
I got a new VPS and carefully followed and ran the installation and ended up with the same error after running the command

```
root@30079:~/evilginx2# sudo evilginx2
sudo: evilginx2: command not found
```
I am totally lost at why this is not working fine anymore.

**Comment by bonyakamara** [comment]
To exhaust all my options, I decided to try installing with Docker.

![docker](https://user-images.githubusercontent.com/75266414/100810157-a8aadb00-33ec-11eb-8969-9540edc0e9ee.png)

That was the result of the installation after pulling and downloading files then trying to make.
I did not understand the last output but I figured out it was an error.
I further continued with trying to run the evilginx2 and I got this other error.

![docker2](https://user-images.githubusercontent.com/75266414/100810274-faebfc00-33ec-11eb-88ad-c58f564c967d.png)

At this point, can you figure out anything could be wrong somewhere? See below my evilginx2 folder

![docker3](https://user-images.githubusercontent.com/75266414/100810442-633add80-33ed-11eb-814e-b318fd527250.png)

Kindly advice and direct.

**Comment by JamesCullum** [comment]
Try `sudo /root/evilginx2/evilginx2` and make sure the file is executable (`chmod +x /root/evilginx2/evilginx2`)

**Comment by bonyakamara** [comment]
`sudo ./evilginx2` and `sudo /root/evilginx2/evilginx2` did it.

Thanks a lot James. I very much appreciate your assistance on this.

Next anticipated challenge would be the acme challenge on generating SSL. I hope what I've read around being an issue won't affect mine :)

**Comment by bonyakamara** [comment]
Thanks @JamesCullum for the lead. Everything worked fine both the SSL generation wasn't any big deal generating. I very much appreciate your time and directions.

**Comment by bonyakamara** [comment]
One question here please @JamesCullum as I don't see it big enough to open a new issue for.

I uploaded a zip containing some phishlets and tried installing but they are not showing up on the list of available phishlets when I run evilginx2. My commands are below.

```
unzip extra.zip
sudo mv phishlets-master/* /usr/share/evilginx/phishlets/
rm -rf extra.zip phishlets-master/
```
If I changed directory to `/usr/share/evilginx/phishlets/` I see them but they don't appear as available for enabling. 
Can you guide me in case the directory schematics or command would be changed from what I have shown above?

**Comment by JamesCullum** [comment]
Hey @bonyakamara, as your questions are quite general about on how to use Linux, I would recommend taking some courses and understanding the different aspects of the OS. While I might be able to see sometimes what your issue is, this is not the right place for IT support and I can hardly help you without having full insight into what and how you are doing it.

**Comment by bonyakamara** [comment]
Well gotten. 

Just didn't want to do anything aside what the usage and installation guides stated.

**Comment by JamesCullum** [comment]
Sure - I've updated the documentation to potentially clarify those things more.

**Comment by negesemuche** [comment]
I try to run the evilginx2 it keep saying

Make: go : No such file or directory
Make : ××× ( makefile:8: build) error 127

Please need help to run it please.
Help me you can write me here or email [muchenegese@gmail.com)
Or telegram @ciabnm
Please someone should please help me.
Thank

**Comment by Quedubs** [comment]
> I am trying to install evilginx2 and after inputting the make command, see attachment for the errors I see. Where is emanating from? Do you think it is my server or from the evilginx release? Kindly assist with explanation.
> 
> ![evil](https://user-images.githubusercontent.com/75266414/100634279-f2f46500-32e3-11eb-9bed-0dca50ab70ec.png)
> 
> #### DO NOT ASK FOR PHISHLETS.
> #### DO NOT ASK FOR HELP CREATING PHISHLETS.
> #### DO NOT ASK TO FIX PHISHLETS.
> #### DO NOT ADVERTISE OR TRY TO SELL PHISHLETS.
> #### EXPECT A BAN OTHERWISE. THANK YOU!
> #### REPORT ONLY BUGS OR FEATURE SUGGESTIONS.

I am facing the same issue presently, can anyone please help

**Comment by scottmahony** [comment]
how can i fix this please



root@ip-17:/home/ubuntu/evilginx2# sudo ./evilginx2
sudo: ./evilginx2: command not found
root@ip-17:/home/ubuntu/evilginx2# sudo /root/evilginx2/evilginx2
sudo: /root/evilginx2/evilginx2: command not found
root@ip-17:/home/ubuntu/evilginx2# chmod +x /root/evilginx2/evilginx2
chmod: cannot access '/root/evilginx2/evilginx2': No such file or directory
