### ISSUE TITLE
 capture tokens

### ISSUE THREAD

**Issue by New1addi** [hash3liZer/evilginx2#19]
Good afternoon. I made my Phishlet everything works fine, through debag I see all cookies, they
are registered in auth_tokens, I get a username and password and do not save cookies, I tried one cookie the same history, auth_urls: also does not help where to drip? auth_urls only on a get request? please help me where to drip. thank you in advance.

**Comment by JamesCullum** [comment]
This report is very difficult to understand for me - what do you mean with "drip"? Maybe you can write in your native language and let it translate by Google Translate?

**Comment by New1addi** [comment]
I just wrote through the translator, sorry for my bad English. Is there any advice, cookies with debug, I see everything, well, he does not save them, tried auth_urls too, there 10 cookies tried at least one result the same. taken from https://github.com/kgretzky/evilginx2/pull/212/commits/0d322964ff520d04f687bcb4797f698ab16fba45 well modified

**Comment by New1addi** [comment]
keys: ['X-BackEndCookie','.*,regexp'] Not work idea?
I've tried almost everything
![555](https://user-images.githubusercontent.com/77670708/105152802-b6d9c580-5b18-11eb-9e5d-8dd3da1826b6.png)

**Comment by JamesCullum** [comment]
You mean it recognizes the stuff but doesn't save the result? This would be related to the phishlet and if it captures all tokens and URLs to recognize that the phishing is complete.

**Comment by New1addi** [comment]
I understand that, well, the capture does not work for me, be it cookies or url, I don't even know what to try

**Comment by JamesCullum** [comment]
I see. I wish you best of luck to find someone to support you with this phishlet specific support. On Github we do not offer support for fixing phishlets, hence I will close the issue on this point.
