### ISSUE TITLE
certificate error 

### ISSUE THREAD

**Issue by pretech86** [hash3liZer/evilginx2#3]
i try to generate certification , i did all steps but couldn't generate it automatically , i download it manually from letsencrypt and put it in evilginx and it work but the facebook page not like the real one but i can catch the token without any problem my web hosting is aws and domain provider is freenom 

please can you help me ?

**Comment by hash3liZer** [comment]
First make sure there is no other instance of evilginx2 running or nginx or apache2. Then remove all the current certificates form /root/.evilginx/crt/. 

Then restart the evilginx2. Hope it will solve the problem.

**Comment by pretech86** [comment]
Thanks for your kindly interest but I did this steps many times , some one told me it’s a firewall problem and you should open port 80 and other one said there’s a problem in the code itself.. i lost 10 days until now .. please can you help

**Comment by Hashtag-AMIN** [comment]
https://cilynx.com/how-to/evilginx2-vs-2fa-phishing/424/

check this
