### ISSUE TITLE
Acme error

### ISSUE THREAD

**Issue by nickrh75** [hash3liZer/evilginx2#7]
Is this tool still working? It used to work fine in the past, but now I always get the following error message when trying to enable a phishlet:

> acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-acct :: urn:ietf:params:acme:error:malformed :: No embedded JWK in JWS header, url:

**Comment by hash3liZer** [comment]
Yes, it is working fine. Make sure some that services are not interfering in the process.
