### ISSUE TITLE
Compiled releases / Docker

### ISSUE THREAD

**Issue by JamesCullum** [hash3liZer/evilginx2#8]
#### PLEASE READ THE POSTING GUIDELINES AND ANSWER THE QUESTION BEFORE POSTING, OTHERWISE ISSUE WILL BE CLOSED AND MARKED AS INVALID

* I hereby declare the following issue is a **[tool specific question/bug report]** and it is **NOT** a help request about creating a phishlet.
* I am fully aware that this is not a customer support portal, I can't demand answers and I'm aware I am using a free tool.
* I am not going to use Evilginx to hax my girlfriend's account or use it for any other illegal purpose.
* I am not trying to set up a domain on FreeNOM (also read the sentence above again).
* I am not a robot.
*(Sorry, if you are an adult and a professional and you had to read this.)*

Please type in "**I CONFIRM**" below if you confirm the sentences above or otherwise make some funny remark:

**I CONFIRM**

Thanks!
--

As the releases of the official one are not updated (and all issues were removed), and this fork appears to be the new maintained version, we should as well create a build pipeline to provide binaries or at least an up-to-date Docker image.

All of this can be set up once and will run automatically and for free, so that people can use it easier.

**Comment by JamesCullum** [comment]
For the docker image, we could use an existing Docker Hub pipeline.
Created PR here: https://github.com/heywoodlh/dockerfiles/pull/1

**Comment by hash3liZer** [comment]
@JamesCullum Sure, I'd like that too. I am currently working on another project. As soon as I am done with that, I'll set it up as well.

**Comment by JamesCullum** [comment]
The Dockerfile has been merged and we can refer to that Docker build: https://hub.docker.com/r/heywoodlh/evilginx2

What about a CI/CD pipeline for testing and releases?
This would make future maintenance easier and prevents issues like the current one, where the current version doesn't match.

If you can add me as a contributor, I can set up the pipelines on TravisCI similar to what I've done with https://github.com/FIDO-Tools/fido2-library

**Comment by hash3liZer** [comment]
Can you pull a request if possible or if you can get me on email?

**Comment by JamesCullum** [comment]
@hash3liZer Sent you another email two days ago - the tests are ready to go and I can set up the pipeline.
However I currently do not have permission to install apps or add releases.
Could you change my permission, so that I can set up Travis?

**Comment by hash3liZer** [comment]
Check your email now.

**Comment by JamesCullum** [comment]
Thanks, received and accepted now.
However the permissions are still insufficient to install apps.

![Error message](https://i.imgur.com/3W7FhX6.png)

EDIT: Looks like this requires admin permission.
However if you install it once, it [should](https://stackoverflow.com/questions/25857012/is-it-possible-to-set-up-travis-for-a-project-for-which-you-are-a-collaborator) allow me to configure it.

**Comment by JamesCullum** [comment]
@hash3liZer Can you install Travis, so that I can configure it?

**Comment by JamesCullum** [comment]
Due to no feedback, I've decided to use Github Actions, as it requires no app installation.
The only thing missing now is adding one secret, that I've sent via email.

**Comment by hash3liZer** [comment]
@JamesCullum Hi, Sorry to have you waited. I was in hospital for some serious health issues. Can you tell me which Secret?

**Comment by JamesCullum** [comment]
Hey @hash3liZer - no worries, hope you're feeling better now :)
I've sent you an email with a secret called "REDDITPASSWORD" and the password to the test account.

**Comment by hash3liZer** [comment]
Gotcha.

**Comment by JamesCullum** [comment]
Great - test pipeline works now and the building one as well 👍
